### ISSUE TITLE
Incorrect header names

### ISSUE THREAD

**Issue by jamesgillanders** [afloers/DREAM_atomic_data#1]
The headers "Upper_g" and "Lower_g" actually correspond to the upper and lower J values of the transitions. These should either be renamed correctly, or be transformed to the statistical weight values

**Comment by afloers** [comment]
Thanks! 
Fixed in [https://github.com/afloers/DREAM_atomic_data/commit/e52161ac1ea18ce28f9e5a063788e10d68d5762f](https://github.com/afloers/DREAM_atomic_data/commit/e52161ac1ea18ce28f9e5a063788e10d68d5762f).
