### ISSUE TITLE
Issue parsing the data for PrII into the data frame

### ISSUE THREAD

**Issue by jamesgillanders** [afloers/DREAM_atomic_data#2]
Line 60:
    df = pd.read_csv(virt_file, delimiter=' ', skipfooter=1, engine='python')

The delimiter doesn't work for parsing the data for Pr II into the df. The wavelength values get dropped and every column is shifted over to compensate.

Swapping the ' ' for '\s+' resolves the issue

**Comment by afloers** [comment]
Fixed in [https://github.com/afloers/DREAM_atomic_data/commit/37569c43019f299046a67cbb15c7eb22ec59c541](https://github.com/afloers/DREAM_atomic_data/commit/37569c43019f299046a67cbb15c7eb22ec59c541).
